### ISSUE TITLE
Parsers not detect multi line strings

### ISSUE THREAD

**Issue by mikezaby** [webhippie/gettext_i18n_rails_js#41]
In some cases we have large strings that is too long to fit in one line, so we want to have something like this
```
__(`Hello, my name is <span class="name">Mike Zaby</span> 
    and this is a very long string`)
```
or in Handlebars
```
{{{__ 'Hello, my name is <span class="name">Mike Zaby</span> 
       and this is a very long string'}}}
```
But the parser is not detecting this strings

**Comment by tboerger** [comment]
I would welcome a pull request to solve that!

**Comment by twang2218** [comment]
I hit the same issue in GitLab, which contains ```__(`xxx`)```. I created an issue in GitLab to workaround the problem. https://gitlab.com/gitlab-org/gitlab-ce/issues/48864

**Comment by tboerger** [comment]
Looks like the regex is not flexible enough yet, I'm open to improvements.

**Comment by himdel** [comment]
`GettextI18nRailsJs::Parser::Javascript#collect_for` is using `each_line`.

The regex seems to allow for newlines just fine (except for `\<newline>` which seems explicitly disallowed in `#arg_regex`), but it never sees the whole multi-line string, only the first line, and does not match because the string ends before the ending quote.

**Comment by himdel** [comment]
`GettextI18nRailsJs::Parser::Handlebars#invoke_regex` is OTOH *not* working with newlines, because it relies on `.*` more heavily. But OTOH `collect_for` runs on the whole file there, so it may be more easy to fix:

```diff
diff --git a/lib/gettext_i18n_rails_js/parser/handlebars.rb b/lib/gettext_i18n_rails_js/parser/handlebars.rb
index e707d10..851616c 100644
--- a/lib/gettext_i18n_rails_js/parser/handlebars.rb
+++ b/lib/gettext_i18n_rails_js/parser/handlebars.rb
@@ -73,7 +73,7 @@ module GettextI18nRailsJs
             .*?
           )
           [}]{2}
-        /x
+        /xm
       end
     end
   end
```

(I'm not sure which of `/xm` or `/xsm` is more correct...)

**Comment by tboerger** [comment]
I would gladly accept a pr including a test to show that it works :)

**Comment by ctrochalakis** [comment]
Hello, is it possible to release a new version including this fix?

**Comment by tboerger** [comment]
That should be possible for sure, I will try to come back to that within the next days

**Comment by ezr-ondrej** [comment]
This still has not been release, right? Could we cut a new release please? it would be very helpful.

**Comment by tboerger** [comment]
I'm not really in ruby development anymore, if somebody wants to takeover the maintenance I'm happy to transfer the project and ownership on rubygems.

In the meantime I need to find the time to review the build process and check if I can roll a release like this is.
