### ISSUE TITLE
Do you follow SemVer? If yes, can you mention it in README?

### ISSUE THREAD

**Issue by pravi** [webhippie/gettext_i18n_rails_js#43]
Unfortunately many projects does not consider a library follows SemVer unless explicitly mentioned. For example gitlab Gemfile wants ~> 1.2.0 (your README also recommends this). Now debian has 1.3.0 and to make gitlab installable I have to maintain a patch to gitlab Gemfile (this adds extra work for every release). If you explicitly states SemVer compliance, then I can ask gitlab to relax this to ~> 1.2 and reduce the maintenance burden. Many projects already responded positively to a similar request https://wiki.debian.org/Teams/Ruby/UpstreamPledge

**Comment by tboerger** [comment]
This gem follows SemVer principles, so feel free to create a PR that explicitly states that within the readme.

**Comment by tboerger** [comment]
Thanks for the PR.
