### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by ekohl** [webhippie/gettext_i18n_rails_js#50]
https://github.com/webhippie/gettext_i18n_rails_js/pull/45 has been merged a long time ago, but no gem release contains this. It would be great if there would be one so we don't need to pin to a git commit (which has way worse caching than gems).

**Comment by tboerger** [comment]
I have release 1.3.1 now.

**Comment by ezr-ondrej** [comment]
Thanks a lot @tboerger ! :heart:
