### ISSUE TITLE
the line number is wrong in the generated pot file

### ISSUE THREAD

**Issue by lidaobing** [webhippie/gettext_i18n_rails_js#8]
all the line number is set to 1

```
#: app/assets/javascripts/materials/others.coffee:1
msgid "Accepted formats: pdf, doc, rtf"
msgstr ""
```

**Comment by tboerger** [comment]
Hopefully I will come back to this in the next days.

**Comment by tboerger** [comment]
As you can see it's not the case for the specs: https://github.com/webhippie/gettext_i18n_rails_js/blob/master/spec/gettext_i18n_rails_js/parser/javascript_spec.rb#L305-L311
If you still find this issue please come back to this issue.
