### ISSUE TITLE
[feature requst] support generate pretty-print js files

### ISSUE THREAD

**Issue by lidaobing** [webhippie/gettext_i18n_rails_js#9]
currently, the generated js file is in one line, how about support pretty print format for this file, it has two pros

1. make the change more clearer in the version control system
2. use less space in the version control system

and because we are using asset pipeline, so the js can be compressed in the production server

**Comment by tboerger** [comment]
Fixed: https://github.com/webhippie/gettext_i18n_rails_js/blob/e2a054bd3794d81f084676c7096ab7d06cb8befa/lib/gettext_i18n_rails_js/tasks.rb#L30
